---
title: 'Lab 1: Question 1'
author: Ian Dela Cruz, Steve Hall, Fengjiao Sun
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
library(haven) # to read SPSS data
library(tidyverse) # if you want more, but still core, toolkit
```

## Data Description
```{r load raw data and select columns, echo=FALSE, warning=TRUE, message=FALSE}
df_raw <- read_sav("anes_timeseries_2020_spss_20210211.sav")
# select variables intending to vote (V201019 = 1); political party (V201018 = 1 or 2); age (V201507x)
# 1 = Dem and 2 = Rep
myvars <- c("V201018", "V201507x")
df_select <- df_raw[myvars]
```

```{r rename columns, echo=FALSE, warning=TRUE, message=FALSE}
df <- df_select %>% 
  rename(
    party = V201018,
    age = V201507x
    )
df <- df[df$party == 1 | df$party == 2 ,] # only keep Dems and Reps
df_clean <- df[df$age != -9, ] # remove refused records
df_clean$party <- ifelse(df_clean$party == 1, 'DEM', 'REP')
```
## Data Viz
```{r histogram of age by party, echo=FALSE, warning=TRUE, message=FALSE}
vline_dat <- df_clean %>% group_by(party) %>% summarize(age_mean = mean(age))
#vline_dat <- data.frame(party=c('D', 'R'), mean=c(mean(df_clean$age),70))
# Add mean lines
p<-ggplot(df_clean, aes(x=age, fill=party)) +
  geom_histogram(position="identity", color='black') +
  geom_vline(aes(xintercept=age_mean), linetype='dashed', data=vline_dat) +
  facet_grid(party ~ .) +
  ggtitle('Age Distribution of Democrats and Republicans in 2020') +
  scale_fill_manual(values= c('dodgerblue3', 'tomato3'))
p
```


The hypotheses are:
$$
H_0: \mu_1 = \mu_2\\
H_1: \mu_1 \ne \mu_2\\
$$

```{r two-sample t-test, echo=FALSE, warning=TRUE, message=FALSE}
t.test(age ~ party, data = df_clean)
```

## Importance and Context
Research question: Are Democratic voters older or younger than Republican voters in 2020?


## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What are some basic features of the data distribution? --> 
<!-- What changes do you make to the data and why? --> 

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance? --> 